### ISSUE TITLE
[Feature]: Add more space properties (fill the gaps between the spaces)

### ISSUE THREAD

**Issue by deemacodes** [shawkidev/etilighties-css#1]
### Describe the solution you would like

I would like you to add more space properties by filling the gaps between the space properties (as I said in the title). For example, add these numbers: 25 - 27 - 29

**Comment by deemacodes** [comment]
Hi @shawkidev, for sure I have used your library. I have done this for the first time in my latest project, and it looks so helpful!

I do not have promising ideas for using the library. I am thinking of building a starter file for the components I use continuously in my React / Gatsby projects. So, if you are interested, it may be a good idea for your library!

**Comment by shawkidev** [comment]
> Hi @shawkidev, for sure I have used your library. I have done this for the first time in my latest project, and it looks so helpful!
> 
> I do not have promising ideas for using the library. I am thinking of building a starter file for the components I use continuously in my React / Gatsby projects. So, if you are interested, it may be a good idea for your library!

That's great! It is incredible to integrate with React. By the way, I have done adding more space properties, and now I am closing this issue 🥳
