### ISSUE TITLE
[Bug]: Why containers width properties do not work in the @media query?

### ISSUE THREAD

**Issue by deemacodes** [shawkidev/etilighties-css#4]
### Describe the bug

Hi there! I have tried using the containers width properties in the CSS media query, and they do not work. Am I incorrectly using them? Or does CSS disallow using CSS custom properties in its media query? And if so, will you provide an alternative way to use them? Thanks!

### OS: [Windows]

Windows

### Browser [FireFox]

FireFox

### Browser Version [96]

97

**Comment by deemacodes** [comment]
By the way, I forget to embed a snippet of my CSS code. Here it is:
`@media only screen and (max-width: var(--container-medium))`

**Comment by shawkidev** [comment]
You can replace the `var()` function with any part of a value in any property on an element. You can not use the `var()` function as property names, selectors, or anything else besides property values. Doing so usually produces invalid syntax.

[Source](https://www.w3.org/tr/css-variables-1)

**Comment by shawkidev** [comment]
> By the way, I forget to embed a snippet of my CSS code. Here it is: `@media only screen and (max-width: var(--container-medium))`


By the way, we did not provide these containers' width properties to let you use them as a media query min or max-width. But, in the upcoming days, we will provide breakpoints properties that you could use the way you mentioned before. Thanks!
